### ISSUE TITLE
automap to sub folders?

### ISSUE THREAD

**Issue by emailjough** [junaidbhura/auto-cloudinary#23]
I have a plugin that is pulling images in to my site from an external CMS and putting them in a sub directory of my media archive. Auto-cloudinary has created a corresponding sub directory inside my Cloudinary auto-mapping-folder.  

So I have images both in /auto-mapping-folder/ and in /auto-mapping-folder/subfolder/

Images in the root directory load fine with Auto-cloudinary, but all the images in this sub directory are now (only recently) returning 404.

When I deactivate auto-cloudinary the images in the subfolder load as expected via wordpress.

Is there a way to either have auto-cloudinary look inside all subfolders, or explicitly set filepaths for multiple directories (both auto-mapping-folder and its child(ren)) ?

thanks

**Comment by junaidbhura** [comment]
@emailjough Thanks for opening the issue.

Sub folders should work out of the box. Can you give me examples of URLs that are working and URLs that are not working?

**Comment by emailjough** [comment]
Not working: 
https://res.cloudinary.com/blueoaks/auto-mapping-folder/ccb/Women-The-Life-Youve-Always-Wanted-wpv_568x142_center_center.jpeg

Note the /ccb/ sub directory above

Working: 
https://res.cloudinary.com/blueoaks/auto-mapping-folder/Blue_Oaks-9_11_16_Baptisms-0154.jpg

Both images can be viewed no problem in my wp media library, and from within my Cloudinary auto-mapping-folder  (e.g. https://res.cloudinary.com/blueoaks/image/upload/v1552045194/auto-mapping-folder/ccb/Women-Ten-Women-of-the-Bible-568x142_center_center.jpg )

**Comment by junaidbhura** [comment]
@emailjough Okay the issue isn't with the plugin, it's a Cloudinary thing:

The job of this plugin is to just create URLs, which it does correctly, as you can see. It's up to Cloudinary to interpret those URLs. For some reason, its not able to find that image.

My guess is because that image is missing in the files. Maybe it didn't copy over or was deleted:
https://res.cloudinary.com/blueoaks/auto-mapping-folder/ccb/Women-The-Life-Youve-Always-Wanted-wpv_568x142_center_center.jpeg

This works just fine:
https://res.cloudinary.com/blueoaks/auto-mapping-folder/ccb/Women-Ten-Women-of-the-Bible-568x142_center_center.jpg
