### ISSUE TITLE
Serve images in next-gen formats like WebP (feature request)

### ISSUE THREAD

**Issue by princehorn** [junaidbhura/auto-cloudinary#28]
Hi Junaid,

imo it's a good idea to serve images from Cloudinary with the transformation parameter "fetch_format => auto" ("f_auto") by default - this would decrease the page load time. Googles Lighthouse Performance test advises to use next-gen formats, too.
Maybe it should be an optional parameter which is enabled in the Admin panel of the Plugin.

Kind regards
JP

**Comment by junaidbhura** [comment]
That's interesting @princehorn thanks for suggesting. I'll take a deeper look at this and keep you updated!

**Comment by junaidbhura** [comment]
Hey @princehorn I'm wondering if this should be best left to the Cloudinary settings? Have you tried this setting in your Cloudinary account?

<img width="507" alt="cloudinary-webp" src="https://user-images.githubusercontent.com/2512525/72196653-08fbfb80-346e-11ea-9d4d-86246bfc28ec.png">

**Comment by princehorn** [comment]
Hi @junaidbhura,

is Cloudinary combining multiple parameters with this Default image quality setting (e.g. fetch_format=auto and quality)? I'm not sure though.

If so, this might be an option as long as you're fine with this preset and you can use this default quality settings for all your websites which are served by your cloudinary account.

**Comment by junaidbhura** [comment]
Hey @princehorn I think for now, we can let this be controlled by the user, rather than adding it to the plugin. Considering there's a setting in Cloudinary to control this - it wouldn't be unimaginable that this would be done by default in the future. Other providers like Jetpack to this already.

As such, I'm closing this issue out. But please feel free to continue this discussion here.

**Comment by leaninonlife** [comment]
This is problematic for me as well. I need granular control of image format and quality. Right now I cannot disable image filetype in order to allow for the automatic format to take over. Removing the extension from the filename would fix some of this. I've also tried manually adding these arguments into the plugin and it does not change anything.

**Comment by junaidbhura** [comment]
@leaninonlife Could you please elaborate your problem, and proposed solution?
