### ISSUE TITLE
Best Practices

### ISSUE THREAD

**Issue by djmtype** [junaidbhura/auto-cloudinary#43]
@junaidbhura I'm trying to follow the best practices. https://github.com/junaidbhura/auto-cloudinary/wiki/Best-Practices

What exactly should be added to the template though other than `id`? I thought the width and height are dynamic, coming from cloudinary, so they shouldn't need to be specified? However, they aren't getting passed down into the attributes. I'm sure I'm doing something wrong.

My template: 
`<?php echo my_theme_image($id = 9) ; ?>`

The output: 

`
<img src="https://res.cloudinary.com/media/mysite/2021/05/photo-unsplash.jpg" width="" height="" srcset="https://res.cloudinary.com/media/w_1000/mysite/2021/05/photo-unsplash.jpg 1000 w, https://res.cloudinary.com/media/w_500/mysite/2021/05/photo-unsplash.jpg 500 w" sizes="(min-width: 1000px) 50vw, 100vw" alt="">
`

**Comment by junaidbhura** [comment]
Hi @djmtype thanks for creating this issue!

I've updated the Best Practices with a simpler example: https://github.com/junaidbhura/auto-cloudinary/wiki/Best-Practices

The examples given there aren't meant to be "working" examples, but more so to illustrate the advantage of keeping your code abstract, and not overly depend on this plugin or Cloudinary, since you may want to switch to some other service at some point.

The exact function or code may depend on your theme or needs.

I'm going to close this issue, but please feel free to continue the discussion here, or alternatively, use the "Discussion" section in this repository: https://github.com/junaidbhura/auto-cloudinary/discussions
