### ISSUE TITLE
Ignore transformations on SVGs?

### ISSUE THREAD

**Issue by djmtype** [junaidbhura/auto-cloudinary#45]
Currently, Cloudinary is converting all images to webp. That's great for the most part except SVGs should be ignored since they're lighter and look better. 

Is there anyway to ignore transformations on SVGs?

**Comment by junaidbhura** [comment]
Hey @djmtype how are you using SVGs? Are you allowed SVGs to be uploaded via the WP Admin?

If you have control over the image, you can just use `full` width, and it will ignore all transformations.

If you don't then you could use the `cloudinary_args` to detect the file extension and disable transformations: https://github.com/junaidbhura/auto-cloudinary/wiki/Filters#cloudinary_args

Since this plugin is designed to work with extensions on WordPress core, SVG isn't supported out of the box. As such, I'm going to close this issue for now. But please feel free to continue this discussion here, and we can re-open the issue if we need to.

**Comment by djmtype** [comment]
@junaidbhura 
I also posted my question to the Cloudinary forum. Basically, if `f_auto` is used, the image will be transformed regardless of format. 

I'm using ACF and am requesting the full image. I don't know if the site editor will upload an svg, so I need to still fallback on WP's auto generated responsive images just in case a png might be used.

`$image_headline = wp_get_attachment_image(get_field('image_headline'), 'full', 0, array('class' => 'image-headline',
'title' => '', 'alt' => ''));`

Here is the rendered image source: 
`
<img width="338" height="182" src="https://res.cloudinary.com/xxxxxxxx/f_auto/site/2021/07/text.svg" data-src="https://res.cloudinary.com/xxxxxxxx/f_auto/site/2021/07/text.svg" class="image-headline lazy loaded" alt="" loading="lazy" title="" data-was-processed="true">
`
