### ISSUE TITLE
Blank page on front side and Error 500 on admin side after activating the plugin.

### ISSUE THREAD

**Issue by byteknight1** [junaidbhura/auto-cloudinary#5]
Just after clicking activate, website became unavailable and all content is gone just header.

**Comment by junaidbhura** [comment]
Hey @byteknight1 this sounds like a PHP error. Could you please check your PHP logs?

This plugin requires at least PHP 5.6 . I'm closing this issue because there aren't too many details provided for me to take any action.

You can feel free to continue to comment on this issue, and we can re-open it if we need to!

**Comment by byteknight1** [comment]
Hello Junaid,

Great plugin but sadly i couldn't make use of it, below is what i encountered. 

The website is running on PHP 7.0, I installed it from WP plugins directory but when clicking activate the website was down throwing 500 error both on admin and user side. 

We have wordfence running on server and my guess installation changes htaccess or tried to modify functions file which caused the error. 

Website was up after removing plugin manually. Hope this will help you escalate the issue and bring best out of the plugin.

**Comment by junaidbhura** [comment]
Hey @byteknight1 thanks for the info!

This plugin does not modify any files at all. It just replaces URLs using hooks, you should be able to turn it off and on without it affecting your site in any way.

Could you check your PHP or Apache logs to see what the error was? This will reveal what the problem really was.
